<?php
return array (
	'logo_path'=>'d:\LOGO_FFMPEG',
	'finished_path'=>'d:\finished',
	'masters_path'=>'m:\\',
	'ntv_path'=>'n:\\',
	'ntv_16x9_path'=>'j:\\',
	'ntv_hd_path'=>'l:\\',
	'hd_path'=>'i:\90',
	'db_path'=>'d:\scripts\db',
	'logo_path'=>'d:\LOGO_FFMPEG',
	'ftp_rutube_file'=>'d:\scripts\tmp\rutube.txt',
	'ftp_rm_file'=>'d:\scripts\tmp\rm.txt',
	'is_ntv'=>array(
		101,
		102,
		104,
		105,
		106,
		107,
		108,
		109,
		111,
		112			
	)
);